### ISSUE TITLE
Variant overrides for package source

### ISSUE THREAD

**Issue by tiran** [python-wheel-build/fromager#302]
I'm maintaining a variant that requires several pre-built wheels. The wheels are not hosted on PyPI. I need a way to configure Fromager to pull the pre-built wheels from the costum package index and to use the custom package index for resolving versions. The options must not influence other variants in the settings file.

**Comment by dhellmann** [comment]
I feel like this has come up before. @shubhbapna probably has thoughts about how to implement it.

**Comment by shubhbapna** [comment]
hmm we have not messed around with the prebuilt variant settings before.
We could change the `prebuilt` field but it would be backward incompatible
```yaml
prebuilt:
    variant:
         package_index: url
         packages:
              - package1
              - package2
```

**Comment by shubhbapna** [comment]
We could decide that based on @tiran's usecase? Or here are couple of other options:

This one tries all the package indices in order for all the listed packages
```yaml
prebuilt:
    variant:
         package_index: 
               - url1
               - url2
         packages:
              - package1
              - package2
```

per package index url config:
```yaml
prebuilt:
    variant:
              - name: package1
                package_index: url
              - name: package2:
                package_index: url
```

**Comment by dhellmann** [comment]
If we need multiples, I like the second form better. It gives the user control, at the expense of some repetition. So maybe we can have

```
prebuilt:
  variant:
    package_index: one_url
    packages:
        - package1
        - name: package2
          package_index: another_url
```
