### ISSUE TITLE
move env settings into per-package settings files

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#315]
Having different file formats for env files vs. other settings can be confusing. We should look at combining the env file with the other settings, after #312 merges.

As part of that, we will have to consider how the current templating resolution approach can be made to keep working. One way would be to structure the YAML so it can still be processed in order. For example

```yaml
envs:
  - name: SOME_VARIABLE
    value: the-value
  - name: OTHER_VARIABLE
    value: ${SOME_VARIABLE}-templated
```
