### ISSUE TITLE
Add package-version-specific changelog to settings

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#317]
- Add a new field `changelog` to the per package setting
- Include a way to specify versions
- We just care about the length of the changelog (the ordering of the entries doesn't matter to us. it is on the user to maintain the ordering)

Agreed upon template:
```yaml
torch:
  changelog:
    "2.3.1":
      - rebuild for xyz

```

**Comment by shubhbapna** [comment]
@dhellmann @tiran regarding the the template for this changelog should we have something like this if we know that one change can affect many versions:

```yaml
torch:
   changelog:
        - name: rebuild xyz
          affected_versions: ["2.3.1", "2.3.2"]
```

or

```yaml
torch:
   changelog:
        rebuild xyz:
               - "2.3.1"
               - "2.3.2"
