### ISSUE TITLE
Implement per variant package settings

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#322]
We need to be able to define per variant package settings. This will probably be a complete revamp of the settings file and we will be able to remove the `prebuilt` field and only have `<package_name>` fields

**Comment by shubhbapna** [comment]
Option 1:

Take advantage of yaml anchors (no new functionality on fromager side essentially)

```yaml
torch:  &torch-base
       build_dir: ...
       resolver_dist: ...
       prebuilt: true

torch-<variant>:
  << : *torch-base
  # override whatever we want
  build_dir: ...
  pre_built: true
```
