### ISSUE TITLE
packagesettings: pypi sources and package settings download_source overrides should allow for validating hashes

### ISSUE THREAD

**Issue by pnasrat** [python-wheel-build/fromager#475]
I  had to use the download_source override for a package build recently and it got me thinking if hash support should be added

I was thinking of something like the following 

```yaml
download_source:
    url: https://egg.test/${canonicalized_name}/v${version}.tar.gz
    destination_filename: ${canonicalized_name}-${version}.tar.gz
    hashes:
      "1.0.1":
        "sha256": e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      "1.0.2":
        "sha256": e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
``` 

That would get added to packagesettings possibly 

```python
# Package source hashes
Hashes = dict[str, str]
VersionHashes = Mapping[PackageVersion, Hashes]
```

However when I started to look at the codebase to add it doesn't look like `_download_source_check` validates the hashes of downloads from pypi, so before proceeding further I wanted to open for discussion.
